# Generated by Django 5.2 on 2025-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_age_profile_bio_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='streaming_service',
            field=models.CharField(blank=True, choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube_music', 'YouTube Music'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='artists',
            field=models.ManyToManyField(blank=True, to='users.artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='users.musicgenre'),
        ),
    ]
